name: macOS Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install -q gcc-arm-embedded mingw-w64 scons
    - name: Build with SCons
      run: |
        scons --jobs "$(sysctl -n hw.ncpu)"
