name: SCons Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Show CPU information
      run: |
        lscpu
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install clang gcc-arm-none-eabi llvm mingw-w64 scons
    - name: Build with SCons
      run: |
        scons --jobs "$(nproc)"
