name: Windows Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install -qq scons
        choco install --limit-output --no-progress diffutils gcc-arm-embedded
    - name: Build with SCons
      run: |
        scons --jobs "$env:NUMBER_OF_PROCESSORS"
